//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCuentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public int ID { get; set; }
        public string DocIdCliente { get; set; }
        public int TipoCuenta { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public decimal InteresesAcumulados { get; set; }
        public string CodigoCuenta { get; set; }
        public bool Activo { get; set; }
    }
}
